### ISSUE TITLE
After the update, links became grey 

### ISSUE THREAD

**Issue by Korean-David** [kepano/obsidian-minimal-settings#15]
links used to be the accent color, but after the update they became grey, so they are barely visible.

**Comment by kepano** [comment]
I have seen this happen once also but haven’t been able to reproduce it. Do you know what the conditions are when this happens? What kind of link are you using, and is this in live preview?

**Comment by Korean-David** [comment]
> I have seen this happen once also but haven’t been able to reproduce it. Do you know what the conditions are when this happens? What kind of link are you using, and is this in live preview?
> […](#)

Hi, it happens in live preview, and markdown links are grey.

**Comment by kepano** [comment]
This is fixed as of 4.3.3 — thanks!
