### ISSUE TITLE
Can the color of texts in square blocks be the accent color? 

### ISSUE THREAD

**Issue by Korean-David** [kepano/obsidian-minimal-settings#16]
Thanks for the quick fix, which solves the issue that links were grey.

But what I really appreciated in the previous version (4.2) was that texts in square blocks (e.g., [content]) were the accent color. But now it is grey. Could it be like before?

**Comment by kepano** [comment]
The accent color version in 4.2 was unintentional, 4.3.3 restores the gray color that was used in prior versions.

If you want to use accent color, you can add a snippet such as:

```
.cm-s-obsidian.is-live-preview .cm-formatting-link + span.cm-link {
color:var(--text-accent);
}
```
