### ISSUE TITLE
Which plugin should I use for theme settings (font size especially)

### ISSUE THREAD

**Issue by davebhc71** [kepano/obsidian-minimal-settings#17]
There seem to be several plugins that modify the various settings for your Minimal theme, including one from a 3rd party Developer, Style Settings. I’m confused as to which One I should be using to achieve the proper results for selecting Font sizes. My main confusion arises from the fact that selecting 17 for the Editor results in a Much larger visual font in Reading. I’m using an iPad Air. I’m uncertain if this is normal to have the size for 17 appear much larger in Reading view than Live Preview. Apologies in advance if I’m mixing up the different ‘views’, I haven’t gotten the names straight in my mind yet.

**Comment by kepano** [comment]
You should only use one of the two plugins. See documentation https://github.com/kepano/obsidian-minimal#companion-plugins

**Comment by davebhc71** [comment]
BINGO!!! You are SO right (of course)! I would suggest putting this sentence in BOLD!!! - 

Note that running both simultaneously may lead to conflicts.

 Thanks again….
Dave B

**Comment by kepano** [comment]
Good idea, that's been updated to clarify.

**Comment by davebhc71** [comment]
While I have you “on the line”, see wording below the Title in the Note below.

**Comment by kepano** [comment]
Screenshots don’t come through when you reply via email

**Comment by davebhc71** [comment]
Submitted in Git.
Thanks
