### ISSUE TITLE
"Relationship lines in Editor" setting is not working

### ISSUE THREAD

**Issue by nshidqi** [kepano/obsidian-minimal-settings#18]
Hi, 

"Relationship lines in Editor" setting is not working meanwhile "Relationship lines in Preview" setting is working
![image](https://user-images.githubusercontent.com/39375111/149608833-8e4783f8-57ee-44fa-9816-40fb12a6c220.png)

![image](https://user-images.githubusercontent.com/39375111/149608858-ef0e526e-ff1e-4e2a-8e06-5fa246508bf1.png)

**Comment by kepano** [comment]
Relationship lines is in the process of being removed from Minimal. Please install Indentation Guides plugin.

**Comment by nshidqi** [comment]
Thank you for the confirmation~
