### ISSUE TITLE
Bug : Colour Scheme - User Settings Not Retained

### ISSUE THREAD

**Issue by StefanoRausch** [kepano/obsidian-minimal-settings#20]
I have chosen the dark "Things" colour scheme.

Both on my mobile devices and on my Windows machine, the setting reverts to the default colour scheme after a re-load or re-start of the application -- the option is still showing "Things", though. I am synching every option and setting except for the active community plugins' list via OS.

It would be great not to reselect the colour scheme every time I ( re- ) launch the application.

Thank you for looking into it.

**Comment by 702573n** [comment]
For me, too, on all devices.

**Comment by kepano** [comment]
This is fixed in 5.0.2 — thanks!

**Comment by StefanoRausch** [comment]
Yeah! And thank you so much for the fast release!
