### ISSUE TITLE
Suggestion: "Focus mode" behaviour & document names

### ISSUE THREAD

**Issue by gabrielwhite** [kepano/obsidian-minimal-settings#21]
Focus Mode is great.

One detail that could be improved is to change the way the document name / top toolbar is shown.

At the moment the document name is hidden, and shows when the mouse cursor is moved to the top of the window.

I'd rather: 

1. The document name shows when I scroll to the top of the document (without requiring mouse intervention), without tools showing
2. When I mouseover the document name in this state, the tools show as well
3. Additionally, that I can summon the document name and tools on mouseover (current behaviour)

This would let me treat the document name as a more integral part of the document, as well as get easy access whenever needed as currently designed.

Thanks!

**Comment by StefanoRausch** [comment]
Great idea, which I second.

**Comment by kepano** [comment]
Have you explore Embedded Note Titles plugin? This may solve the first item on your list.

**Comment by gabrielwhite** [comment]
Thanks @kepano! This solves 80% of the problem (I wish it Embedded Note Titles let me edit the title).

Please keep this suggestion in the back of your mind as you continue to develop your plugin.

**Comment by kepano** [comment]
Inline titles is now a part of Obsidian 0.16
