### ISSUE TITLE
[5.0.4] Text labels for primary navigation results in a list of "Plugin"

### ISSUE THREAD

**Issue by xplatinum** [kepano/obsidian-minimal-settings#23]
![image](https://user-images.githubusercontent.com/55301375/151845253-065372ff-d5cb-42f4-b749-e72d05aa7351.png)

**Comment by kepano** [comment]
Please follow the instructions in the new bug report template. I need that information to be able to reproduce and debug the issue.

**Comment by xplatinum** [comment]
Where can I find the new report template?

Thanks

**Comment by kepano** [comment]
When you create a new bug it’s the prefilled text in the main text field in GitHub

**Comment by xplatinum** [comment]
Not sure if I'm doing something wrong but It's empty for me. Sorry I'm new
to this.

[image: image.png]

-
Vincent Charette

**Comment by kepano** [comment]
Oops! I see you're in a different repo than I thought (Minimal plugin not Minimal theme)...

It would be useful to have the debug info. It can be accessed in Obsidian with Ctrl/Cmd-P, enter "Show debug info", and click "Copy to clipboard".

I am guessing there is a plugin interfering somewhere

**Comment by xplatinum** [comment]
Here you go! I made sure I disabled every community plugins prior to reproducing the issue.

> SYSTEM INFO:
	Obsidian version: v0.13.19
	Installer version: v0.13.19
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 9
	Plugins enabled: 1
		1: Minimal Theme Settings

> RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please try to make the issue happen in the help vault or disable community plugins.

**Comment by xplatinum** [comment]
After keeping all the plugins turned off and restart obsidian the correct labels appeared. I'm turning the plugins one by one and restarting the app in between each. I'll keep you posted.

**Comment by xplatinum** [comment]
After turning off all plugins, restarting the app, and re-enabling all of them I no longer have the issue. I will check if I can fix the issue on my other PC by doing the same thing.

**Comment by xplatinum** [comment]
Simply restarting the app on my other PC resolved the issue. 🙏

**Comment by kepano** [comment]
The issue is that you were on the old version of Obsidian. The text labels requires 0.13.22 or above
