### ISSUE TITLE
Numbers appear as emojis

### ISSUE THREAD

**Issue by HaleTom** [kepano/obsidian-minimal-settings#24]
**Describe the bug**
Numbers appear as emojis, even inside note text

**To reproduce**
Enable the plugin, see all numbers being replaced:

**Expected behavior**
Rumbers stay as their UTF-8 actual representation

**Screenshots**
![image](https://user-images.githubusercontent.com/13854417/152675874-6ceb8c99-6dd1-4220-96cc-371d9f78effb.png)

**Debug info (please complete the following information):**
Paste your debug info below, which can be accessed in Obsidian with Ctrl/Cmd-P, enter "Show debug info", and click "Copy to clipboard".
```
SYSTEM INFO:
	Obsidian version: v0.13.23
	Installer version: v0.13.23
	Operating system: #1 SMP PREEMPT Thu Jan 20 13:58:19 UTC 2022 5.15.16-1-MANJARO
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 10
	Plugins enabled: 9
		1: Add Codemirror matchbrackets.js
		2: Vimrc Support
		3: Improved VimCursor
		4: Relative Line Numbers
		5: Emoji Toolbar
		6: Emoji Shortcodes
		7: Theme Picker
		8: Hider
		9: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Comment by kepano** [comment]
I am not able to reproduce this issue. Please disable plugins and snippets. You likely have a conflict coming from one of the plugins you are using.
