### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Alexnoj** [kepano/obsidian-minimal-settings#25]
- active line
- blockquote styles
- bold links
- block click on checkbox like [?]
- clutter free heading
- embeds settings like 
  - hide title
  - hide head
- list styles preview and edit mode
-- option add minimal settings to Customizable Sidebar Plugin

Thanks!

**Comment by kepano** [comment]
Please review documentation at https://minimal.guide and see the [Minimal theme repo](https://github.com/kepano/obsidian-minimal). Most of these capabilities already exist via Style Settings plugin. The features that are missing should be created as separate individual feature requests on the Minimal repo.
