### ISSUE TITLE
Changing line height doesn't do anything on Linux

### ISSUE THREAD

**Issue by laurastephsmith** [kepano/obsidian-minimal-settings#29]
**Describe the bug**
Changing the "line height" doesn't do anything at all. I'm on Gnome 40 on Debian.

**To reproduce**
1. Go to Minimal Theme Settings.
2. Change line height from 1.5 to either 2, 3 or 4.
3. No change to space between lines of notes in either live preview or reading view.
4. Close and reopen Obsidian gives same result.

**Debug info**
SYSTEM INFO:
	Obsidian version: v0.13.33
	Installer version: v0.13.23
	Operating system: #1 SMP Debian 5.15.15-1 (2022-01-18) 5.15.0-3-amd64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 27
	Plugins enabled: 3
		1: Divide & Conquer
		2: Contextual Typography
		3: Minimal Theme Settings

Thanks!

**Comment by kepano** [comment]
I am unable to reproduce this issue

**Comment by laurastephsmith** [comment]
Thanks for trying to reproduce. I've just realised that none of the settings do anything for me! I can change them (toggle the toggles, change numbers in boxes). The changes I make save okay (I can go out of the settings modal and back in again and they're how I left them). But I can't find a single setting in the plugin that actually affects what it's supposed to.

I'm using a dozen other plugins and they work fine. This seems a really odd bug! Do you have any suggestions for how I can debug it? Are you able to test it on Linux? Thanks ever so much for your help.

**Comment by kepano** [comment]
Maybe this is a dumb question but are you using Minimal Theme?

1. Open Obsidian Settings
2. Go to Appearance and click Manage
3. Under community themes search for "Minimal" and click Use

**Comment by kepano** [comment]
According to your debug info it says `Community theme: none`

You need to have Minimal Theme enabled for Minimal Theme Settings plugin to work.

**Comment by laurastephsmith** [comment]
Oh my, now I feel silly. I've only been using Obsidian for a week or so, and not sure where I got this from but thought that Minimal was the default theme! Evidently no such thing as a dumb question! Evidently the same reason for obsidian-minimal#214.

I'll get my coat... thanks for your help :D
