### ISSUE TITLE
Feature request: Change highlight colour

### ISSUE THREAD

**Issue by pwal2425** [kepano/obsidian-minimal-settings#3]
Hi,

Thanks for the great theme and plugin.

I have set up the plugin to show the same colours that I use across my system, but unfortunately this makes the highlight colour almost impossible to see. Would it be possible to have a separate setting to adjust just the text highlight colour?

Thanks 😊

**Comment by kepano** [comment]
I would recommend doing this via a CSS snippet for now. There are so many elements in Obsidian that can have custom colors that adding a setting for each would make the settings unnavigable.

The variables you're looking for are here https://github.com/kepano/obsidian-minimal/blob/master/obsidian.css#L260

**Comment by pwal2425** [comment]
Thanks. I'm a bit of a beginner here, but I am sure someone has done an idiot's guide to CSS for Obsidian...
