### ISSUE TITLE
Export to PDF does not include custom font

### ISSUE THREAD

**Issue by wxxedu** [kepano/obsidian-minimal-settings#32]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:
- Minimal Theme
- Minimal Theme Settings plugin (or Style Settings plugin, but not both)
- Contextual Typography plugin

**Describe the bug**
I have set the custom fonts in the Minimal Theme Settings plugin, and it shows correctly on both the preview view and the editor view. However, it does not work with the PDFs exported from the Minimal Theme. 

**To reproduce**
1. Go to 'Settings'
2. Click on 'Minimal Theme Settings'
3. Scroll down to 'Custom Fonts'
4. Change the fonts
5. Export to PDF

**Expected behavior**
The PDFs would have the correct fonts. 

**Screenshots**
<img width="804" alt="CleanShot 2022-03-17 at 10 11 00" src="https://user-images.githubusercontent.com/36021591/158722790-86f16f70-9303-40ff-80bc-c361d5088cc2.png">

The font in the Editor:
<img width="747" alt="CleanShot 2022-03-17 at 10 13 54" src="https://user-images.githubusercontent.com/36021591/158722852-3a2b6004-8da6-47b3-b9f0-9a7be2717dac.png">

The font in the PDF:
<img width="768" alt="CleanShot 2022-03-17 at 10 13 27" src="https://user-images.githubusercontent.com/36021591/158722817-48ccea5c-a5d8-4ecc-87b2-c3b723995621.png">

**Debug info (please complete the following information):**
N/A

**Comment by ygxxii** [comment]
Colorful headings seem not included either.

**Comment by kepano** [comment]
This is not related to Minimal it's an Obsidian limitation. See related Obsidian forum topics
