### ISSUE TITLE
Separate font size for editor / viewer

### ISSUE THREAD

**Issue by orlp** [kepano/obsidian-minimal-settings#33]
I like to have my editor in a different font than my viewer. But not every font agrees on what '16 points' of font size means.

I looked around but I couldn't find a way to set a different font size for the text in the editor v.s. the text in the viewer. Assuming I am not just being stupid and missed it, I would love to see that.

**Comment by kepano** [comment]
You can achieve this via a CSS snippet

See implementation of the font size here:
https://github.com/kepano/obsidian-minimal/blob/master/src/scss/obsidian/fonts.scss#L17-L22
