### ISSUE TITLE
Setting to adjust indentation size of list

### ISSUE THREAD

**Issue by jakemkc** [kepano/obsidian-minimal-settings#34]
**Is your feature request related to a problem? Please describe.**
Hi Kepano,

I just tried to use the Minimal Theme and it's awesome.

With the minimal theme setting and styling setting plugins, it is possible to change many simple visuals without CSS knowledge, such as font family, font size, spacing.

I played around with a few themes and think minimal theme is the best! 

However, I found the indentation size of list is too big for me and didn't able to find a setting to modify it.

**Describe the solution you'd like**
It will be great to have a simple setting to allow users to adjust indentation size. There is a default and users can adjust the number.

For example, this is what minimal theme shows:
![040122 minmial](https://user-images.githubusercontent.com/18485734/161304197-2d0f1b1b-a405-406e-8590-72c2bdaea503.png)

This is what California Coast shows:
![040122 california](https://user-images.githubusercontent.com/18485734/161304196-6e5ea9bf-5c0a-48cb-974e-e48fa6ae6400.png)

Thanks!

Jake

**Comment by kepano** [comment]
Are you talking about the horizontal distance from the left side? Or the vertical distance between bullets?

the latter can be changed using Style Settings plugin

**Comment by jakemkc** [comment]
Hi Kepano,

Sorry I didn't make it clear enough. I am talking about the horizontal distance from the left side.

![040122 minmial 2](https://user-images.githubusercontent.com/18485734/161313358-8722fd0f-9b55-4e0b-b5b9-62ad5511ca8a.png)

Jake

PS: Also love the setting to adjust line spacing in Style Settings plugin!

**Comment by kepano** [comment]
This is now available in Style Settings
