### ISSUE TITLE
Disappearing cursor with Colorful Cursor active

### ISSUE THREAD

**Issue by thoresson** [kepano/obsidian-minimal-settings#39]
**Describe the bug**
Yesterday I suddenly lost the cursor in Obsidian. After trying to disable and one-by-one enable plugins, it seems like the problem is with Minimal Theme Settings.

**To reproduce**
With Colorful Cursor active, the cursor disappears. With the setting off, the cursor appears again.

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.14.9
	Installer version: v0.12.19
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 31
	Plugins enabled: 23
		1: Better Word Count
		2: Block Reference Counter
		3: Breadcrumbs
		4: Buttons
		5: Calendar
		6: Dataview
		7: Emoji Toolbar
		8: ExcaliBrain
		9: Excalidraw
		10: Frontmatter Tag Suggest
		11: Hotkeys++
		12: Hover Editor
		13: Kanban
		14: Lapel
		15: Natural Language Dates
		16: Obsidian42 - BRAT
		17: Obsidian42 - Text Transporter
		18: Outliner
		19: Periodic Notes
		20: Readwise Official
		21: Templater
		22: Zoom
		23: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by kepano** [comment]
This issue has already been reported and closed. Please update theme.
