### ISSUE TITLE
incorrect block <style id=minimal-theme>...</style>

### ISSUE THREAD

**Issue by numero6fromthevillage** [kepano/obsidian-minimal-settings#41]
Hello,

line 487 of javascript : 
el.innerText = "\n        body.minimal-theme{\n          --font-normal:" + this.settings.textNormal + "px;\n          --font-small:" + this.settings.textSmall + "px;\n          --line-width:" + this.settings.lineWidth + "rem;\n          --line-width-wide:" + this.settings.lineWidthWide + "rem;\n          --max-width:" + this.settings.maxWidth + "%;\n          --max-col-width:" + this.settings.maxColWidth + ";\n          --text:" + this.settings.textFont + ";\n          --text-editor:" + this.settings.editorFont + ";\n          --font-ui:" + this.settings.uiFont + ";\n          --font-monospace:" + this.settings.monoFont + ";\n          --accent-h:" + this.settings.accentHue + ";\n          --accent-s:" + this.settings.accentSat + "%;}\n      ";

is incorrect : the CR are translated into \<br\> tags !

You must double escape the CR's or just delete them :

```
el.innerText = "body.minimal-theme{--font-normal:" + this.settings.textNormal + "px; --font-small:" + this.settings.textSmall + "px; --line-width:" + this.settings.lineWidth + "rem; --line-width-wide:" + this.settings.lineWidthWide + "rem; --max-width:" + this.settings.maxWidth + "%; --max-col-width:" + this.settings.maxColWidth + "; --text:" + this.settings.textFont + "; --text-editor:" + this.settings.editorFont + "; --font-ui:" + this.settings.uiFont + "; --font-monospace:" + this.settings.monoFont + "; --accent-h:" + this.settings.accentHue + "; --accent-s:" + this.settings.accentSat + "%;} ";
```

This is a very classic mistake among beginners !
Have a good day.

**Comment by kepano** [comment]
Thanks! Fixed in 5.2
