### ISSUE TITLE
theme variable override built-in variable in v0.14.5+

### ISSUE THREAD

**Issue by aidenlx** [kepano/obsidian-minimal-settings#43]
in latest v5.2.6, `--font-monospace` is [still overriden by plugin on load](https://github.com/kepano/obsidian-minimal-settings/blob/6b89adee8252fbe773868fb17a9c91537d77362c/main.ts#L562-L563). probably should at least provide an option to disable these conflict injection for user who set font in obsidian? or maybe don't inject if it's set to empty string?

related: https://github.com/kepano/obsidian-minimal-settings/pull/37

**Comment by aidenlx** [comment]
btw you can consider merge #38, it only update the build method and should not affect the source code.

**Comment by kepano** [comment]
Right now custom fonts are not available on Obsidian Mobile, so I am waiting for the release to finalize the font changes

**Comment by aidenlx** [comment]
good news! custom fonts is available in 1.2.2+ 🎉 

update log from [App Store](https://apps.apple.com/us/app/obsidian-connected-notes/id1557175442)
> 1.2.2 (Jun 7, 2022)
> - Includes all new functionality and bug fixes up to Obsidian Desktop v0.14.15.
> - Fixed rename vault functionality gets stuck.
> - You can now setup Obsidian Sync right from the starting screen.
> - Fixed black bar at the bottom on iPad when using external keyboard.
> - Tapping the three dot more options icon now brings up the menu related to this file, rather than the right sidebar. You can get to the right sidebar by long-holding this icon, or swiping from the right.
> - Obsidian can load all locally available fonts on your device.
> - Long-holding buttons that triggers an action (like the three dot menu) now triggers it after holding instead of triggering it when the finger is released.
> - Fixed app freezing when resuming from another app when using a large vault.

**Comment by aidenlx** [comment]
confirmed that the issue is fixed in v5.3.0
