### ISSUE TITLE
Phone - search Field (German button names too long) 

### ISSUE THREAD

**Issue by johans3** [kepano/obsidian-minimal-settings#44]
**Before you open a bug report**
Disabled plugins and snippets  = **yes**

Update to the latest versions:
- Minimal Theme
- Minimal Theme Settings plugin
- Contextual Typography plugin
**All up to date**

**Confirm that the bug is not present when Minimal theme is off**
**Obsidians default theme** isn't affected, just if Minimal (theme) is active ( plugins/css are off) 

**Describe the bug**
**The search and replace field** on phone is messy for the German language, because button names are too long, the x to close the query is missing completely in the vertical phone view 

**To reproduce**
1. invoke the command palette 
2. type search (search current file) 
3. buttons are too narrow, because German button names are longer than the English counterpart

**Expected behavior**
Obsidians default search and replace field is pretty big but ideal for a phone
On the other hand, Minimal is elegant and even the English buttons are pretty narrow each other
I highly recommend to replace the button names with arrows to save space so that all buttons should fit within the same space for all possible languages. 

**Screenshots**
![Screenshot_20220520-193142](https://user-images.githubusercontent.com/48620536/169581899-9099eaef-b670-45fb-8dc8-b28135867df9.png)
![Screenshot_20220520-193133](https://user-images.githubusercontent.com/48620536/169581920-f7a6d3f7-49e7-468c-8da9-cb6a0826977a.png)
![Screenshot_20220520-193019](https://user-images.githubusercontent.com/48620536/169581926-d543b949-40ef-48b6-8999-2d159e64e3cd.png)

**Debug info (required):**
-

**Comment by kepano** [comment]
Fixed in 5.2.8
https://github.com/kepano/obsidian-minimal/releases/tag/5.2.8
