### ISSUE TITLE
Typing cursor doesn't work when I enable Obsidian minimal settings

### ISSUE THREAD

**Issue by smio102** [kepano/obsidian-minimal-settings#46]
Very recently my typing cursor stopped displaying in Obsidian. I mean the thin flashing line that indicates where in the file you are inserting text.

I've tested all plugins and confirmed that it's Obsidian Minimal Settings causing this as the issue is not there when I disable it and restart.

Debug info:
```
SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.13.19
	Operating system: Windows 10 Pro 10.0.19044
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 4
	Plugins enabled: 1
		1: Minimal Theme Settings

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

edit: after further testing I found that it's caused by the "fancy cursor" option. My accent colour is very different from background so I'm confused as to why it would make the cursor not be visible. However disabling it fixes the issue

**Comment by kepano** [comment]
You need to update Obsidian and the theme
