### ISSUE TITLE
Link overriding heading color

### ISSUE THREAD

**Issue by Ashvin9567** [kepano/obsidian-minimal-settings#48]
**Is your feature request related to a problem? Please describe.**
Using "Colorful headings" under "Features" in the minimal theme settings overrides the color for headings to orange. This is an issue as H3 headings (Amber colored) can be mistaken for H2 headings (orange colored) when this override of color occurs.

**Screenshots**
![image](https://user-images.githubusercontent.com/44165241/177801614-3257ea91-7e81-4196-b028-6ea1440cac4e.png)
If it's of any help then I am using the Gruvbox color scheme

**Describe the solution you'd like**
I can think of 2 solutions:
1. Changing the color prioritory from links to headings.
2. Add a setting which allows an individual to choose which gets prioritory.

**Comment by kepano** [comment]
This is not really an issue as much as personal preference. Consider turning off colorful headings and using Style Settings to adjust your preferences for heading and link colors

**Comment by kepano** [comment]
That is the intended behavior. If you want to override it you would need to do it via a CSS snippet.
