### ISSUE TITLE
Checkboxes not displaying with Kanban plugin

### ISSUE THREAD

**Issue by pwal2425** [kepano/obsidian-minimal-settings#5]
Hi, thanks again for the lovely theme and corresponding plugin ☺

I've recently started using the [Kanban plugin](https://github.com/mgmeyers/obsidian-kanban) by @mgmeyers but have noticed that the checkbox feature doesn't render properly with the minimal theme.

Below is how some example text renders with the normal theme and with minimal. You can see a tiny dot next to the completed item, but it is pretty tough to see and you cannot mark the item as completed or not. Any ideas?

Thanks again!

### Example text

```
## Kanban list

- [x] Completed item
- [ ] Item not yet completed
```

### Normal theme:

![image](https://user-images.githubusercontent.com/83947681/130789390-ada58c8a-6cc9-4d39-b575-9356932619de.png)

### Minimal:

![image](https://user-images.githubusercontent.com/83947681/130789421-f74d0ceb-f551-431c-93ec-1ea6e867e240.png)

**Comment by pwal2425** [comment]
Update: it turns out that the little red dot does work as a checkbox, but you need to get the cursor directly over it, which takes some doing

**Comment by pwal2425** [comment]
Yes. I also turned off the minimal theme settings plugin to make sure that it wasn't being triggered by a change I had made.

**Comment by pwal2425** [comment]
Update: I opened a Kanban board from a new vault in minimal theme and with just the kanban plugin installed - the issue persisted. I am using the latest version of Obsidian for Windows 10.

**Comment by kepano** [comment]
This should be fixed if you download the latest version of Minimal theme
