### ISSUE TITLE
Linked and Unlinked Mentions - style issue

### ISSUE THREAD

**Issue by jebeaudoin** [kepano/obsidian-minimal-settings#52]
**Confirm that the bug is not present when Minimal theme is off**
Confirmed

**Describe the bug**
When "Colorful Active States" is toggled on in light mode, the filenames of backlinks (displayed at bottom of note) are invisible (i.e. white on white background) unless you hover over them. Active states elsewhere, such as in the file navigator, display the accent color correctly. See images below.

**To reproduce**
Open note with backlinks
Toggle backlinks to display at bottom of note
Toggle on Color Active States in Minimal Theme Settings

**Expected behavior**
I expect to see the filenames of both mentioned and unmentioned links.

**Screenshots**
![Linked mention filenames](https://user-images.githubusercontent.com/10992411/187486737-6aa11d25-85c2-4825-81ed-012d621672a3.png)

Hover Version
![Hover version](https://user-images.githubusercontent.com/10992411/187486799-18db9050-5ba2-46d4-a35c-a01703c9aed2.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.16.0
	Installer version: v0.15.6
	Operating system: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 21.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 43
	Plugins enabled: 41
		1: Obsidian42 - BRAT v0.6.34
		2: Pandoc Plugin v0.2.5
		3: Periodic Notes v0.0.17
		4: QuickAdd v0.5.5
		5: Readwise Official v2.0.1
		6: Recent Files v1.3.3
		7: Smart Random Note v0.2.1
		8: Tag Wrangler v0.5.3
		9: Style Settings v0.4.10
		10: Todoist Plugin v1.9.0
		11: Kanban v1.3.17
		12: Day Planner v0.5.8
		13: Commander v0.1.0
		14: Trim Whitespace v0.2.2
		15: Text Format v1.8.1
		16: Alias from heading v1.0.12
		17: Folder Note Core v1.3.5
		18: Bartender v0.5.7
		19: AidenLx's Folder Note v0.16.4
		20: Regex Find/Replace v1.2.0
		21: Divide & Conquer v0.4.0
		22: Advanced URI v1.24.0
		23: Better PDF Plugin v1.4.0
		24: Better Word Count v0.8.1
		25: Buttons v0.4.16
		26: Calendar v1.5.10
		27: cMenu v1.1.2
		28: Copy Block Link v1.0.4
		29: Custom Frames v2.4.3
		30: Dataview v0.5.43
		31: Expand Bullet v1.0.2
		32: Find orphaned files and broken links v1.6.1
		33: Hotkeys for templates v1.4.3
		34: Icon Folder v1.3.31
		35: Natural Language Dates v0.6.1
		36: Obsidian better Internal Link Inserter v1.0.0
		37: Obsidian Leaflet v5.0.3
		38: Timelines v0.3.2
		39: Toggl Track v0.9.0
		40: Vault Statistics v0.1.2
		41: Minimal Theme Settings v6.0.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
This is fixed if you update to the latest version of the theme and plugin
