### ISSUE TITLE
Code Block settings not working with Obsidian 16.0

### ISSUE THREAD

**Issue by nickchomey** [kepano/obsidian-minimal-settings#53]
**Describe the bug**
I have set the color and font size for Code Blocks using the Minimal Theme Settings + Style Settings plugins, but the color and size don't change - both in live preview and full preview modes. This only happened after updating to 16.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/88559987/188223844-ff3aa449-e09f-4c9b-97dd-e9132f58dc03.png)

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v0.16.1
	Installer version: v0.15.9
	Operating system: Windows 10 Home 10.0.22622
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 71
	Plugins enabled: 3
		1: Style Settings v0.4.11
		2: Minimal Theme Settings v6.0.0

**Comment by kepano** [comment]
This is fixed if you upgrade to Minimal 6.0.4
