### ISSUE TITLE
Can't click to drag window with several tabs, "Text labels for primary navigation" enabled, and Hidden window frame (macOS)

### ISSUE THREAD

**Issue by gtg922r** [kepano/obsidian-minimal-settings#54]
**Confirm that the bug is not present when Minimal theme is off**
- tried on fresh-ish vault, with minimal theme, minimal theme settings, and hider plugins. No snippets active
- Confirmed no bug with default theme

**Describe the bug**
- With Obsidian >= 0.16 on macOS I am unable to click to drag the Obsidian window when the following conditions are true:
  - Hidden window frame style
  - Enough tabs open to fill the title bar area
  - "Text labels for primary navigation" active

Note:
- If I close enough tabs to have significant blank space in the title bar, clicking in that blank space *does* work to drag
- If I turn "Text labels for primary navigation" off, normal click to drag behavior returns
- If i switch to the default theme, normal click to drag behavior returns

**To reproduce**
- Enabled hidden window frame style (and reload)
- Activate minimal theme and minimal theme settings
- Turn "Text labels for primary navigation on"
- Open enough tabs to fill title area
- Try to click basically anywhere in the title area to drag the window

**Expected behavior**
- Window should be able to be dragged around by clicking any blank space in the title-bar area

**Screenshots**

https://user-images.githubusercontent.com/1195174/191110276-61311f7c-e52c-426d-97c5-e28264647444.mov

**Debug info (required):**
```
SYSTEM INFO:
	Obsidian version: v0.16.3
	Installer version: v0.15.8
	Operating system: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 21.4.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 7
	Plugins enabled: 7
		1: Style Settings v0.4.11
		2: Advanced Tables v0.17.3
		3: Dataview v0.5.46
		4: Calendar v1.5.10
		5: MySnippets v1.2.3
		6: Hider v1.2.1
		7: Minimal Theme Settings v6.0.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by aravindk100** [comment]
I am also facing the same issue with minimal plugin.

**Comment by SisyphusSmile** [comment]
A similar issue is now happening to me in Obsidian v.1.5.3. When "Text labels for primary navigation" is enabled, there is only a small area on the left side of the window frame that I can click to drag the window. Occurs whether or not the sidebar is visible. Can drag as normal with the right sidebar and empty tab space, when it's available.

Anyone else experiencing this?

Minimal Theme v7.4.6
Minimal Theme Settings v7.3.1

**Comment by kepano** [comment]
this will be fixed in the next version of Minimal
