### ISSUE TITLE
Image columns in lists

### ISSUE THREAD

**Issue by sector101010** [kepano/obsidian-minimal-settings#55]
**Is your feature request related to a problem? Please describe.**
Consecutive images are not displayed in columns inside a list item.

**Describe the solution you'd like**
Make consecutive images in a list item display in columns.
Respect newlines inside the list item.

**Comment by kepano** [comment]
I don't understand the request. Is this related to image grids?

**Comment by nilfric** [comment]
Xorry, yes image grids. Prepend the image markdown with `- ` to move them into a list. Result is that the grid is not rendered anymore, but instead the images appear as in vanilla Obsidian, one on top of the other.

**Comment by kepano** [comment]
I don't plan to support grids inside lists
