### ISSUE TITLE
Colorful headings overrides Style Settings for H1 headings

### ISSUE THREAD

**Issue by gabrielwhite** [kepano/obsidian-minimal-settings#57]
**Describe the bug**
If you have Colorful Headings enabled AND H1 color in Style Settings, the H1 color selection in Style Settings is not shown. If you try to do the same for any other heading level, the H2, H3, H4, etc the color selection in Style Settings are shown.

**To reproduce**
- Enable Colorful Headings
- Customise the H1 color in Style Settings
- Customise the H2 color in Style Settings

You will observe that the selected H1 color is not shown, while the H2 color is shown.

**Expected behavior**
That Style Settings override "Colorful headings" consistently.

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v1.0.0
	Installer version: v1.0.0
	Operating system: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:07 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8110 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 15
	Plugins enabled: 12
		1: Shortcuts extender v2.2.0
		2: Pandoc Plugin v0.4.1
		3: Smart Typography v1.0.18
		4: Markdown prettifier v0.1.4
		5: Style Settings v0.4.12
		6: Ozan's Image in Editor Plugin v2.1.4
		7: LanguageTool Integration v0.3.0
		8: Advanced Tables v0.17.3
		9: File Explorer Note Count v1.2.0
		10: Recent Files v1.3.3
		11: Minimal Theme Settings v6.0.5
		12: Editor Syntax Highlight v0.1.3

**Comment by kepano** [comment]
The Colorful headings feature is essentially saying "use the color scheme colors for headings" so this is the intended effect

**Comment by gabrielwhite** [comment]
Understand that it might be intended, but the behaviour is inconsistent. I can't override H1, but I can override H2, etc.

It took me a lot of head scratching to work out what the problem was because I could customise all of the headings but not H1 while Colorful Headings was enabled.

I suggest you make the behaviour consistent.

**Comment by kepano** [comment]
I see. I will investigate that.

**Comment by kepano** [comment]
So I just tested this and I am not able to reproduce what you are describing. If "Colorful headings" is turned on I cannot change the heading colors for H2 etc in Style Settings

**Comment by kepano** [comment]
This issue should be fixed if you update the theme to 6.0.12
