### ISSUE TITLE
Strange Code Block Rendering with "True Black" Contrast

### ISSUE THREAD

**Issue by camccaffrey** [kepano/obsidian-minimal-settings#58]
**Describe the bug**
Code blocks do not render as they did prior to v1.0.0. Screenshot provided below. Under the conditions described, it renders an extra box around the code with no margins and with the same background color as code blocks under default contrast. Functionality does not seem to be affected.

**To reproduce**
1. Enable Minimal Theme *and* Minimal Theme Settings plugin
2. Toggle dark mode
3. Set background contrast to "True Black"

**Expected behavior**
Code blocks rendered without an extra box.

**Screenshots**
![image](https://user-images.githubusercontent.com/89548503/195921766-c8f680d4-15ff-404c-a8f1-ccdc304af556.png)

**Debug info (required):**
SYSTEM INFO:
	Operating system: ios 15.5 (Apple iPhone)
	Obsidian version: 1.4.0 (80)
	API version: v1.0.0
	Login status: not logged in
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 11
	Plugins enabled: 1
                1: Minimal Theme Settings v6.0.5

**Comment by kepano** [comment]
This is an issue with Obsidian not Minimal. Will be fixed in next version of Obsidian.
