### ISSUE TITLE
[Question] Should colorful headings ON effect the inline-title color?

### ISSUE THREAD

**Issue by trainbuffer** [kepano/obsidian-minimal-settings#59]
-Obsidian 1.0.2
-Minimal Theme 6.1.0
-Minimal Theme Settings 6.1.0

With Minimal Theme Settings 'Colorful headings' turned on, my inline-title font color picks up the same red (#e4374b) as my H1s. I rarely use H1s so noticed it immediately. Changing the inline-title color back to black is easy on my end (Style Settings or snippet), but I wondered if this is intentional or not. Thanks.

**Comment by kepano** [comment]
Yes this is intentional since the inline title uses the H1 style. This is native to Obsidian not a Minimal thing.

**Comment by trainbuffer** [comment]
Understood. It makes sense now. Cheers!
