### ISSUE TITLE
Where are theme settings stored?

### ISSUE THREAD

**Issue by PhilLovesToCode** [kepano/obsidian-minimal-settings#60]
When I make changes using this plugin, where does it store them?  After I customize the Minimal theme on one computer, I want to move those customizations to my other computers. What file(s) do I need to copy over to the other computers so they will have the same customizations?
Thanks,
Phil

**Comment by PhilLovesToCode** [comment]
You closed my issue without providing any response.  Could you please answer my question?

**Comment by kepano** [comment]
All plugins store their settings in data.json in the relevant folder of the plugin within .obsidian — this is not specific to Minimal Theme Settings

Please use the appropriate channels for help — you can use the Obsidian forum or Discord.
