### ISSUE TITLE
Opacity on images

### ISSUE THREAD

**Issue by digidoor** [kepano/obsidian-minimal-settings#61]
I'm using the minimal dark theme and it applies a dimming effect to all images. (Actually, it might be translucence that looks like dimming due to a dark bg, but nevermind.) I *really* dislike this, but I was able to fix it by adding the following lines in Minimal/theme.css:
```css
.theme-dark .markdown-preview-view img {
    opacity: 1;
}
```
The problem is that obsidian seems to pick and choose when this works. Sometimes I come back to a note and the images are dimming again. Sometimes it works at startup, sometimes it doesn't. I don't know what that's all about but if you could add it as a toggle to the settings menu that would be perfect.

**Comment by kepano** [comment]
That is more complicated than necessary. You can simply target the variable directly with a snippet

```
body {
--image-muted: 1;
}
```

**Comment by digidoor** [comment]
Simpler is better, but that snippet doesn't work for me for whatever reason. Seems like it should, but no dice.
