### ISSUE TITLE
Metadata template capabilities.

### ISSUE THREAD

**Issue by SalahAdDin** [kepano/obsidian-minimal-settings#62]
**Is your feature request related to a problem? Please describe.**
We would like to add some extra metadata like playing(played, unplayed, playing) or modify the existing one, so we can filter media on dataviews.

We tried to do this by templating also the metadata, but it didn't work.

**Describe the solution you'd like**
Enabling templating also the metadata as **book search** already does.

**Comment by kepano** [comment]
This is unrelated to Minimal — you should explore the Obsidian Forum or Discord for help with this issue.
