### ISSUE TITLE
Atom theme - nav-file-tag's color makes it less legible

### ISSUE THREAD

**Issue by PurposeRefined1179** [kepano/obsidian-minimal-settings#63]
Very minor issue, well not even an issue, I could do this in the style settings or from css snippets, but I think it would be better if it's updated from the plugin itself:
Atom:
![image](https://user-images.githubusercontent.com/120597920/225075944-50ae93cd-d66b-4dde-9009-555d4a1ec7c1.png)

Default Minimal:
![image](https://user-images.githubusercontent.com/120597920/225076139-3e1a71e8-cca0-4024-b4d9-f74e74c54cf1.png)

Default Obsidian:
![image](https://user-images.githubusercontent.com/120597920/225076314-165f9a9d-0d64-4127-a7d7-833c7ead9255.png)

I think you need to change this colour to something more lighter:
![image](https://user-images.githubusercontent.com/120597920/225077337-7106cefb-cf29-41c8-b9a6-a01e7e7831d6.png)

**Comment by kepano** [comment]
Will be fixed in the next version of Minimal theme (7.8.0)
