### ISSUE TITLE
Maximum line width % setting does't work

### ISSUE THREAD

**Issue by wengyk** [kepano/obsidian-minimal-settings#65]
My Mininal theme version is 7.0.5.
Maximum line width % setting does't work.

**Comment by kepano** [comment]
I need more detail to work with. Please use the bug report template, with steps to reproduce and debug info.

**Comment by wengyk** [comment]
> I need more detail to work with. Please use the bug report template, with steps to reproduce and debug info.

Thanks for your reply, I found the cause of the bug, it turns out that I turned off the "readable line length" option in setting.
