### ISSUE TITLE
Hide window buttons in focus mode

### ISSUE THREAD

**Issue by uziam** [kepano/obsidian-minimal-settings#67]
**Is your feature request related to a problem? Please describe.**
No, this is an enhancement.

**Describe the solution you'd like**
A toggle in settings to also hide window buttons (minimize, maximize, close) in focus mode when window frame style is set to hidden.

**Comment by kepano** [comment]
I don't plan to do something like that for accessibility reasons. However you could potentially create this effect using the plugin Electron Window Tweaker by setting a negative position
