### ISSUE TITLE
List indentation causes confusion and is wildly inconsistent between Source and Preview modes

### ISSUE THREAD

**Issue by jptechnical** [kepano/obsidian-minimal-settings#71]
# List indentation causes confusion and is wildly inconsistent between Source and Preview modes

## **Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme
- Minimal Theme Settings plugin

## **Confirm that the bug is not present when Minimal theme is off**

With the Default theme this is not present, or at least the visual indentation is negligible or simply an aftereffect of applying a style to the list elements.

## **Describe the bug**

When using the Minimal Theme, a visual indentation is inserted on lists, both ordered and unordered. This obscures the actual indents and leads to confusion. This is fine in Live Preview, you expect the content to be messed with, but in source mode there should be no structural changes to the code.

Alternatively, when viewed in Preview mode the lists actually are half a character into the left-hand gutter, the opposite of an indent. 

The result of flipping between source and preview modes is wildly different and very confusing.

## **To reproduce**

With Minimal Theme enabled, create a list. The list example below contains indentation on the unordered sublist only, the rest of the ordered list is not intended to be indented. It clearly appears to be indented.

## **Expected behavior**

I expect to see, particularly in source code view, a fairly true representation of the content. The markdown below is an example. This, although parsed by GitHub is still fairly true to the underlying code. 

This code:

``````markdown
```
​We got this alert about a file possibly containing passwords on your system during a routine content scan. If this does have passwords in it, we suggest the following. 
1. Move all passwords to a password manager (like Keeper)  
2. Replace any passwords with references to the password manager.  
  - For instance, instead of "The password for XYZ Corp is: ABC!@#"  
  - Replace it with: "The password for XYZ Corp is in Keeper under Clients > XYX Corp"
4. Delete any files that contain the password so that they can not be retrieved.
```
``````
Should produce this output:
```markdown
​We got this alert about a file possibly containing passwords on your system during a routine content scan. If this does have passwords in it, we suggest the following. 
1. Move all passwords to a password manager (like Keeper)  
2. Replace any passwords with references to the password manager.  
  - For instance, instead of "The password for XYZ Corp is: ABC!@#"  
  - Replace it with: "The password for XYZ Corp is in Keeper under Clients > XYX Corp"
4. Delete any files that contain the password so that they can not be retrieved.
```

## **Screenshots**
Instead, this is the view of the code above in source mode and live preview mode. 
![image](https://github.com/kepano/obsidian-minimal-settings/assets/12360898/4074a7b4-e8e7-41ed-beed-ae3b33511dcb)

Oddly enough, when in reading mode, the opposite occurs, the list elements are actually nearly a 1/2 character width into the left-hand gutter.
![image](https://github.com/kepano/obsidian-minimal-settings/assets/12360898/cbe3615c-4f9e-41c7-9bb7-26370889bee1)

## **Debug info (required):**

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 22.6.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.0.13
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Obsidian Enhancing Export v1.1.8
		2: Vimrc Support v0.9.0
		3: Auto Link Title v1.2.5
		4: Relative Line Numbers v2.0.1
		5: Hider v1.3.1
		6: Style Settings v1.0.7
		7: Minimal Theme Settings v7.3.0
		8: Kanban v1.5.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
If this is still an issue please re-open on the theme repo
