### ISSUE TITLE
Tag pills in Properties show wrong when changing Line height

### ISSUE THREAD

**Issue by l2eused** [kepano/obsidian-minimal-settings#72]
**Describe the bug**
When changing Line height (2 for example) and having ≥2 line in tags property (while using Properties in document), the last line tag pill will showing ugly padding (see screenshot) this padding will increase along with Line height.

**To reproduce**
in app settings
- Editor > Display > Properties in document > visible

in plugin settings
- Minimal Theme Settings > Typography > Line height > set to 2 (for example)

**Expected behavior**
in last line of tags property should show as normal tag padding.

**Screenshots**
normal (when Line height is 1.5)
![Screenshot_20231123-162436.png](https://github.com/kepano/obsidian-minimal-settings/assets/94383254/9b546758-13d4-4240-89ac-cb824d0b0a1e)

issue (when Line height is 2)
![Screenshot_20231123-162539_Obsidian.png](https://github.com/kepano/obsidian-minimal-settings/assets/94383254/f96a5da7-5a2c-480c-af45-9592696d6f98)

**More info**
Obsidian Mobile 1.4.16 version
Minimal Theme 7.3.5 version
Minimal Theme Settings 7.3.0 version

Android 13 AOSP based rom

**Comment by kepano** [comment]
Theme issues should be tracked on the theme
