### ISSUE TITLE
In Obsidian 1.5.3 + Minimal Theme Setting 7.3.1 , there is a misalignment issue with the positioning of tables.

### ISSUE THREAD

**Issue by alexinea** [kepano/obsidian-minimal-settings#73]
In Obsidian 1.5.3 + Minimal Theme 7.4.3 + Minimal Theme Setting 7.3.1, there is a misalignment issue with the positioning of tables.

I have already disabled all my CSS Snippets.

This is my Minimal Theme style settings (about Table) in "Style Settings" plugin:

<img width="593" alt="42adbfd19cacc65ebcffd13e7df14ad" src="https://github.com/kepano/obsidian-minimal-settings/assets/980129/903ac7f7-1847-46ed-8bea-e1d71ce90ca2">

> I chose "always fill."

Then, the table will display like this:

<img width="1232" alt="361bf826ef73068fd6a648bde6cd876" src="https://github.com/kepano/obsidian-minimal-settings/assets/980129/b5a0d7b3-7d0e-4901-acd4-43ad922168f3">

After testing, I discovered that this issue does not occur in the default theme or other themes. If I select the "Fit to line width" option (default value), the table displays correctly (indicating that, by default, tables in the Minimal Theme do not experience misalignment). However, when I select the "Overflow line width" or "Always fill" options, the table's positioning becomes misaligned.

![image](https://github.com/kepano/obsidian-minimal-settings/assets/980129/f9c63616-753e-49b5-a679-748102e7148b)

 Additionally, using `cssclasses` does not resolve this misalignment issue.

Debug ingo:

```
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.26016
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.3
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 9
		1: Thino v2.1.4
		2: Admonition v10.1.1
		3: Advanced URI v1.38.1
		4: Dataview v0.5.64
		5: Hider v1.3.1
		6: Minimal Theme Settings v7.3.1
		7: Obsidian42 - BRAT v0.12
		8: Style Settings v1.0.7
		9: Sortable v0.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

When I took the screenshot, I had multiple plugins enabled, and I needed to eliminate the interference of the plugins, so I closed all but nine of them, but the problem persisted. Therefore, some of the plugins that appear in my screenshot are not included in the list of plugins in the debug info because I had already disabled them.

**Comment by alexinea** [comment]
Addition: The tables generated by DataView do not experience positional displacement.

**Comment by kepano** [comment]
Please keep issues like this in the Minimal repo

**Comment by alexinea** [comment]
The information has been synchronized to another issue.

Looking forward to getting it fixed. thx:)
