### ISSUE TITLE
read view does not correspond to edit view

### ISSUE THREAD

**Issue by Beedmoser** [kepano/obsidian-minimal-settings#78]
- Minimal Theme

**Describe the bug**
Everything works fine and editing is the same as vew mode exept padding of paragraphs.

**To reproduce**
See enclosure

**Expected behavior**
see enclosure

**Screenshots**
If applicable, add screenshots to help explain your problem

**Debug info (required):**

![Screenshot 2024-01-30 092053](https://github.com/kepano/obsidian-minimal-settings/assets/121089493/bc15334c-8bd7-48f0-99dd-6fcd5bde45ea)
SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.4.7
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 8
		1: Dataview v0.5.64
		2: Number Headings v1.16.0
		3: Regex Find/Replace v1.2.0
		4: Text Format v2.5.0
		5: Advanced Paste v2.7.0
		6: Excel to Markdown Table v0.4.0
		7: Auto Link Title v1.5.3
		8: Minimal Theme Settings v7.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by kepano** [comment]
You can adjust this in Style Settings → Text

**Comment by Beedmoser** [comment]
Sorry to be a bit slow here.

Settings = Minimal Theme Settings?

Under Typography I find Line hight but I want to adjust the padding (which works in view but not in Edit Mode).


Beat Moser

Bergstrasse 9
8322 Madetswil

FON +41 79 257 96 00

Von: Steph Ango ***@***.***>
Gesendet: Dienstag, 30. Januar 2024 15:59
An: kepano/obsidian-minimal-settings ***@***.***>
Cc: Beat Moser ***@***.***>; Author ***@***.***>
Betreff: Re: [kepano/obsidian-minimal-settings] read view does not correspond to edit view (Issue #78)


You can adjust this in Style Settings → Text

**Comment by kepano** [comment]
No it's a separate plugin called Style Settings.
Please check out the documentation here:
https://minimal.guide/plugins/style-settings
