### ISSUE TITLE
Feature request: option to reset "accent color" to default

### ISSUE THREAD

**Issue by davidculley** [kepano/obsidian-minimal-settings#8]
Would you please add the option to reset the accent color to the same color Minimal Theme uses when the plugin "Minimal Theme Settings" is not installed/enabled?

**Comment by geoelectric** [comment]
Adding to this, I'd really love the option on *every* setting (or at least the ones that aren't checkboxes) to reset to default. The Style Settings plugin has this, as does the default UI for many options, and it's very useful.

But the Accent color is probably the biggest deal. This one had me uninstalling and reinstalling the plugin to restore.

**Comment by kepano** [comment]
This is now available in Obsidian 0.16
