### ISSUE TITLE
minimal setting unexpectedly controls page width on mobile phone

### ISSUE THREAD

**Issue by MugenLee** [kepano/obsidian-minimal-settings#81]
**Before you open a bug report**
yes

- Minimal Theme
- Minimal Theme Settings plugin

**Confirm that the bug is not present when Minimal theme is off**
yes

**Describe the bug**

1. editor > Readable line length is the opposite
When you open it, page  is max width
When you close  it, page  is limit width

2.  when i close the "minimal setting" plugin ， it become normal 
minimal setting unexpectedly controls page width，the "maximum line witdth %" can controls page width

you can see the video

https://github.com/kepano/obsidian-minimal-settings/assets/91043731/d9f60eae-ec9f-4986-800f-5edabfe311c2

**To reproduce**
you can see the video:

**Expected behavior**
when Readable line length  is open ,the page width will be display normal

**Screenshots**
you can see the video:

**Debug info (required):**
sorry i don`t konw how to  set this on mobile phone

**Comment by kepano** [comment]
I am not able to reproduce. Please try updating the app/plugins. I'll need the debug info which you can get from the command palette.

**Comment by MugenLee** [comment]
> I am not able to reproduce. Please try updating the app/plugins. I'll need the debug info which you can get from the command palette.

Hello kepano, thank you for your works to  making the minimal  so good. I have been using minimal 

my minimal theme and minimal setting have updtated to the latest version

obsidian mobile : v1.5.8(126)
obsidian PC:  v1.5.8
minimal setting: v7.3.1
minimal theme: v7.5.1

and ,  I know "ctrl+shift+i" on PC, but I don't know how to "debug info debug from the command" on my phone,
can you tell me how?
