### ISSUE TITLE
Minimal Typography Toggle Please!

### ISSUE THREAD

**Issue by MaxTheSpy** [kepano/obsidian-minimal-settings#82]
**Is your feature request related to a problem? Please describe.**

Minimal is a great theme but Im having issues or conflicts with other plugins such as [Editor with Slider](https://github.com/MugishoMp/obsidian-editor-width-slider) which also controls line width and such. 

**Describe the solution you'd like**
I would love it if the typography settings that deal with line width, height, text size etc, was able to be toggled on and off so that other plugins could take control over minimal.

**Comment by kepano** [comment]
I'm not planning to add support for this plugin. My recommendation would be to not use Minimal Theme Settings if that other plugin is more important to you.
