### ISSUE TITLE
wrong display caused by ``symbol and a picture

### ISSUE THREAD

**Issue by flamesky80** [kepano/obsidian-minimal-settings#83]
When type some text with `` symbol, and a local picture following the paragraph.
Select 'Reading View' mode, the display goes wrong.
If add a empty line between text and picture, the display will be correct.
I turned off/on all my plugins one by one, finally determined that the problem was caused by ‘Minimal Theme Settings’.
Please fix it. Thanks a lot !!!
![001](https://github.com/kepano/obsidian-minimal-settings/assets/15180023/0bafa71b-ae8c-4360-9d42-86c6dea5972f)
![002](https://github.com/kepano/obsidian-minimal-settings/assets/15180023/16b45728-b067-47ef-b801-78239435e59e)

**Comment by kepano** [comment]
Try turning off image grids

**Comment by flamesky80** [comment]
It's works ! Thanks !!!

**Comment by flamesky80** [comment]
It's works ! Thanks !!!
