### ISSUE TITLE
Strict embed style not working as expected

### ISSUE THREAD

**Issue by Nick468** [kepano/obsidian-minimal-settings#84]
**Describe the bug**
Enabling the _Use strict embed style globally_ setting results in inconsistent behaviour. I want to embed a document containing a list into another list.

1. Has the correct identation, but you have to add an empty line between the list and the embedded content.
```
- This is some regular text

![[Test 2]]
```
![grafik](https://github.com/kepano/obsidian-minimal-settings/assets/40504392/b2836f0d-1a9a-4ced-b492-3019bebadf78)

Removing the empty line leads to 2. and 3:
```
- This is some regular text
![[Test 2]]
```
2. Editing View: This is close to what I want, but the indentation is slightly off.
![grafik](https://github.com/kepano/obsidian-minimal-settings/assets/40504392/46568b5f-8ee9-4cf7-9ec0-d6c39dc47a65)
3. Reading view: The text has incorrect indentation
![grafik](https://github.com/kepano/obsidian-minimal-settings/assets/40504392/d63c4fab-8080-421e-b4f5-60a1d36085c6)

**Expected behavior**
I want the identation to be correct like in 1, but without the neccessety to add an empty line.

**Debug info (required):**
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.5.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 2
		1: Style Settings v1.0.8
		2: Minimal Theme Settings v7.5.0

**Comment by kepano** [comment]
This is not related to the Minimal Theme Settings plugin — if it's still an issue it should be opened on Minimal theme repo.
