### ISSUE TITLE
Changing the lightness of everything in the left sidebar

### ISSUE THREAD

**Issue by daxmonson** [kepano/obsidian-minimal-settings#9]
This is great. I have a question:

Would it be possible to add the ability to change the lightness of “folder names," “note titles” and basically all UI elements like the star symbol, plug-in icons, etc in the left-sidebar? Already have the monitor set to dark and it makes it hard to see UI elements and folders.

I poked around inside the internals with the console open, using the inspector, then hovering over the element saw the color is #808080 and I’d like it to be #878787 for folder names and note titles etc. This doesn't seem to universally apply to them all though, only specific folders etc.. I'd just add some custom CSS snippet there, but not seeing how to change any and all elements in your theme for left sidebar to something lighter. Thanks for any pointers or considering that as an option.

**Comment by kepano** [comment]
I would definitely encourage you to explore CSS snippets, there is a ton of reference around how to use them on the [Obsidian forum](https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133) and you can always ask for help in the Obsidian Discord.

You can also explore the obsidian.css for this theme and create your own CSS snippet that modifies the following variables:

```
--icon-muted:1;  /* expects a 0.5 to 1 value */
--text-muted:;
--text-faint:;
```
